### ISSUE TITLE
Merging causes huge hang and memory usage

### ISSUE THREAD

**Issue by H0L0GH05t** [py-pdf/PyPDF2#189]
Windows 7 64bit
Python 3.4.2
PyPDF2 1.24
Reportlab 3.1.44

I am using reportlab to create a page with hyperlinks, then merging that pdf page over an existing page with PyPDF2. Usually there is no problem, but with this certain pdf it hangs so long and eats up my memory until I am at 97% physical memory usage! If this was the only process running it might be okay, but this is happening on a server with many other processes. It ends up throwing "out of memory" error or the process will time out.

I created a stand-alone script version that is a clone of the code in my project to test. I found that a normal page takes about 7 seconds to run the script, with about 5 seconds on merging. The original pdf was 586 KB and after merging the file was 1,162 KB. The problem page, however, took about 7 minutes to run with more than half of the time spent merging. The python process grew to half of my memory in size (about 2.3 GB) before the process finally finished. The original page was 9.67 MB, and after merging the link page the file was 32 MB. File size issues aside, the memory usage growing so large is very bad for my server. Is this problem occurring simply because the file is large? Or is there some underlying issue here? 

Any help on this would be appreciated! Thank you!

[here was a link which no longer works]

Here is the clone stand-alone script version of the code in my project:

```python
output = PdfFileWriter()
output_path = 'BAZ01-0303-019-MERGED.pdf'
debug_article_links = True

path = "BAZ01-0303-019.pdf"
input_streams = []
input = PdfFileReader(open(path, "rb"), strict=False)
input_streams.append(input.stream)
number_of_pages = input.getNumPages()
if number_of_pages > 0:
    input_page = input.getPage(0)

    #crop the pdf to the trimbox first                    
    input_page.cropBox.upperLeft  = input_page.trimBox.upperLeft
    input_page.cropBox.upperRight = input_page.trimBox.upperRight
    input_page.cropBox.lowerLeft  = input_page.trimBox.lowerLeft
    input_page.cropBox.lowerRight = input_page.trimBox.lowerRight

    size = {'width': float(input_page.mediaBox.getWidth()), 
        'height': float(input_page.mediaBox.getHeight())}
    margin = {'left': 0, 
                'top': 0,
                'right': 0,
                'bottom': 0}
    scale_factor = 10.0

link_page = None
input_stream = None

##### Make pdf link page #####

packet = io.BytesIO()
can = canvas.Canvas(packet, pagesize=(size['width'], size['height']))

region_left = scale_factor * 10
region_bottom = scale_factor * 10
region_right = scale_factor * 80
region_top = scale_factor * 0
x1 = float(region_left + margin['left'])
y1 = float(size['height'])/2
x2 = float(region_right + margin['left'])
y2 = float(size['height'])

width = float(region_right - region_left)
height = float(region_bottom - region_top)

r1 = (x1, y1, x2, y2)  # this is x1, y1, x2, y2 with lower left as origin (x1=0, y1=0)

url = "www.google.com"
can.linkURL(url, r1, thickness=8, color=colors.green)
can.setStrokeColorRGB(1,0,1)
can.setFillColorRGB(1,0,1)
if debug_article_links:
    can.rect(x1, y1, width, height, stroke=1, fill=0)
    can.drawString(x1+3, y2+2, u'test')
else:
    can.drawString(x1+3, y2+2, u' ')

can.showPage()
can.save()
packet.seek(0)

try:
    new_pdf = PdfFileReader(packet)
    input_stream = new_pdf.stream
    link_page = new_pdf.getPage(0)
except Exception as e:
    print(e)

####Merge link page####

if input_stream != None:
    input_streams.append(input_stream)
if link_page != None:
    input_page.mergePage(link_page) #THIS IS WHERE IT HANGS!
output.addPage(input_page)

if os.path.exists(output_path):
    os.remove(output_path)
output_stream = open(output_path, "wb")

output.write(output_stream)
output_stream.close()
for input_stream in input_streams:
    input_stream.close()
```

**Comment by claird** [comment]
On Mon, Mar 16, 2015 at 09:53:37AM -0700, akaiame wrote:
			.
			.
			.
> Windows 7 64bit
> Python 3.4.2
> PyPDF2 1.24
> Reportlab 3.1.44
> 
> I am using reportlab to create a page with hyperlinks, then merging that pdf page over an existing page with PyPDF2. Usually there is no problem, but with this certain pdf it hangs so long and eats up my memory until I am at 97% physical memory usage! If this was the only process running it might be okay, but this is happening on a server with many other processes. It ends up throwing "out of memory" error or the process will time out.
> 
> I created a stand-alone script version that is a clone of the code in my project to test. I found that a normal page takes about 7 seconds to run the script, with about 5 seconds on merging. The original pdf was 586 KB and after merging the file was 1,162 KB. The problem page, however, took about 7 minutes to run with more than half of the time spent merging. The python process grew to half of my memory in size (about 2.3 GB) before the process finally finished. The original page was 9.67 MB, and after merging the link page the file was 32 MB. File size issues aside, the memory usage growing so large is very bad for my server. Is this problem occurring simply because the file is large? Or is there some underlying issue here? 
> 
> Any help on this would be appreciated! Thank you!
> 
> [Here's a link to the problematic pdf page on my google drive](https://drive.google.com/open?id=0B6dXxBfAqiuRbU1UY01jb2hXODQ&authuser=0)
> 
> Here is the clone stand-alone script version of the code in my project:
> 
>     output = PdfFileWriter()
>     output_path = 'BAZ01-0303-019-MERGED.pdf'
>     debug_article_links = True
>     
>     path = "BAZ01-0303-019.pdf"
>     input_streams = []
>     input = PdfFileReader(open(path, "rb"), strict=False)
>     input_streams.append(input.stream)
>     number_of_pages = input.getNumPages()
>     if number_of_pages > 0:
>         input_page = input.getPage(0)
>     
>         #crop the pdf to the trimbox first                    
>         input_page.cropBox.upperLeft  = input_page.trimBox.upperLeft
>         input_page.cropBox.upperRight = input_page.trimBox.upperRight
>         input_page.cropBox.lowerLeft  = input_page.trimBox.lowerLeft
>         input_page.cropBox.lowerRight = input_page.trimBox.lowerRight
>         
>         size = {'width': float(input_page.mediaBox.getWidth()), 
>             'height': float(input_page.mediaBox.getHeight())}
>         margin = {'left': 0, 
>                     'top': 0,
>                     'right': 0,
>                     'bottom': 0}
>         scale_factor = 10.0
> 
>     link_page = None
>     input_stream = None
>     
>     ##### Make pdf link page #####
>     
>     packet = io.BytesIO()
>     can = canvas.Canvas(packet, pagesize=(size['width'], size['height']))
>     
>     region_left = scale_factor * 10
>     region_bottom = scale_factor * 10
>     region_right = scale_factor * 80
>     region_top = scale_factor * 0
>     x1 = float(region_left + margin['left'])
>     y1 = float(size['height'])/2
>     x2 = float(region_right + margin['left'])
>     y2 = float(size['height'])
>     
>     width = float(region_right - region_left)
>     height = float(region_bottom - region_top)
>     
>     r1 = (x1, y1, x2, y2)  # this is x1, y1, x2, y2 with lower left as origin (x1=0, y1=0)
>     
>     url = "www.google.com"
>     can.linkURL(url, r1, thickness=8, color=colors.green)
>     can.setStrokeColorRGB(1,0,1)
>     can.setFillColorRGB(1,0,1)
>     if debug_article_links:
>         can.rect(x1, y1, width, height, stroke=1, fill=0)
>         can.drawString(x1+3, y2+2, u'test')
>     else:
>         can.drawString(x1+3, y2+2, u' ')
>         
>     can.showPage()
>     can.save()
>     packet.seek(0)
>     
>     try:
>         new_pdf = PdfFileReader(packet)
>         input_stream = new_pdf.stream
>         link_page = new_pdf.getPage(0)
>     except Exception as e:
>         print(e)
> 
>     ####Merge link page####
> 
>     if input_stream != None:
>         input_streams.append(input_stream)
>     if link_page != None:
>         input_page.mergePage(link_page) #THIS IS WHERE IT HANGS!
>     output.addPage(input_page)
>     
>     if os.path.exists(output_path):
>         os.remove(output_path)
>     output_stream = open(output_path, "wb")
>     
>     output.write(output_stream)
>     output_stream.close()
>     for input_stream in input_streams:
>         input_stream.close()
			.
			.
			.
We take this report particularly seriously.  We'll have more to say, within the week.

**Comment by akaiame** [comment]
Any news on this yet? This is a big deal for my project so I'd like an update if possible.

**Comment by claird** [comment]
On Fri, Apr 03, 2015 at 04:14:37PM -0700, akaiame wrote:
			.
			.
			.
> Any news on this yet? This is a big deal for my project so I'd like an update if possible.
			.
			.
			.
No news--but I'll try to work on it tonight.

**Comment by akaiame** [comment]
Just checking in... any progress?

**Comment by tiznull** [comment]
We just ran into the same problem, tried everything to work around the issue but nothing has worked. Any ideas on what is causing this?

**Comment by ajshankar** [comment]
We're also experiencing similar problems and would love to hear about any solutions or workarounds. In our case, a single 1000-page, 400MB document uses over 35GB of RAM before it crashes.

**Comment by claird** [comment]
Hello,

Thank you for your question, comments, and/or concerns regarding PyPDF2.
All of our PyPDF2 users are very important to us.  Unfortunately at this
present time we are in the process of regrouping our office.  Your
questions are very important to us but regretfully we will not be able to
address any issues regarding PyPDF2 until later this fall.  However, if
this is an urgent matter and you need immediate assistance please respond
to this email and we will try our best to accommodate your needs sooner.
My apologies for the inconvenience.  Thank you for your patience.

Sincerely,

Selma Kishwar

Phaseit, Inc.

selmaikishwar@gmail.com

**Comment by mikeymop** [comment]
Has this been revisited? It's been a few years and I am experiencing this same issue.

**Comment by MartinThoma** [comment]
Picking just random PDFs (and a lot of those!) I was not able to see any issue: https://github.com/py-pdf/PyPDF2/issues/160#issuecomment-1155632510 

Was it maybe fixed?

**Comment by MartinThoma** [comment]
I assume this is fixed. Please let me know if it isn't.

**Comment by tiznull** [comment]
You will need to test using different encodings to be sure. We found it was certain characters that caused the issue. So I would not assume it’s fixed. Or maybe just close the ticket and see if it comes up again.

**Comment by dmitrhji** [comment]
The problem is not solved if the size of the resulting file is larger than 2GB.

**Comment by MartinThoma** [comment]
@dmitrhji Please describe further what you're doing and which hardware (CPU, RAM, maybe HDD / SSD) you're using.

Why is that PDF so big? Is it mostly images? Lots of pages / text? Maybe some embedded content or complex graphics?

**Comment by RNogales94** [comment]
I also have the same bug, I can provide sample files for debugging.

`start = time.time()
  packet = io.BytesIO()
  can = canvas.Canvas(packet, pagesize=letter)
  # add watermark corner
  can.setFillColorRGB(0.3, 0.5, 0.3, 0.5)
  can.drawString(3, 20, watermark_text)
  can.save()

  # move to the beginning of the StringIO buffer
  packet.seek(0)

  # create a new PDF with Reportlab
  print("Create empty pdf file with watermark")
  new_pdf = PdfReader(packet)
  # read your existing PDF
  print(f"Read file {pdf_path}")
  existing_pdf = PdfReader(open(pdf_path, "rb"))
  num_pages = len(existing_pdf.pages)
  print(f"File {pdf_path} loaded in memory. File has {len(existing_pdf.pages)} pages")
  output = PdfWriter()
  # add the "watermark" (which is the new pdf) on the existing page
  for i, page in enumerate(existing_pdf.pages):
      print(f"Merge page {i}/{num_pages}")
      page.merge_page(new_pdf.pages[0]) # This is where the memory leak happens (I think)
      output.add_page(page)`

**Comment by MartinThoma** [comment]
@RNogales94 Please provide those sample files. With the example I used no issue occured.

**Comment by vduran-eprensa** [comment]
I have a similar problem. In my application I have to make some sort of collage from various PDFs joining them onto a single page. Where there are too many "fragments" merge starts taking more and more time every iteration per fragment I join.
Hope this helps.

**Comment by stefan6419846** [comment]
Please consider opening a new issue with complete code and ideally some reproducing example file(s) as well as some details on the system and delays to observe. Otherwise this possibly already hard to see performance issue is rather impossible to reproduce.
